server:
  port: 8081
spring:
  application:
    name: user_service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db_users_store
    username: root
    password: mysqladmin
    pool:
      initial-size: 5
      max-size: 20
