server:
  port: 8082
spring:
  application:
    name: order_service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db_orders_Store
    username: root
    password: mysqladmin
    pool:
      initial-size: 5
      max-size: 20
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: order-service
  cloud:
    gateway:
      routes:
        - id: orders
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
      cors:
        allowedOrigins: "http://localhost:4200"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        allowedHeaders:
          - "*"
        allowCredentials: true