spring:
  application:
    name: order_service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db_orders_Store
    username: root
    password: mysqladmin
    pool:
      initial-size: 5
      max-size: 20